from selenium import webdriver
import time
import pickle
import os
import requests


chrome_options = webdriver.ChromeOptions()
# chrome_options.accept_untrusted_certs = True
# chrome_options.assume_untrusted_cert_issuer = True
# chrome_options.add_argument("--no-sandbox")
# chrome_options.add_argument("--disable-impl-side-painting")
# chrome_options.add_argument("--disable-setuid-sandbox")
# chrome_options.add_argument("--disable-seccomp-filter-sandbox")
# chrome_options.add_argument("--disable-breakpad")
# chrome_options.add_argument("--disable-client-side-phishing-detection")
# chrome_options.add_argument("--disable-cast")
# chrome_options.add_argument("--disable-cast-streaming-hw-encoding")
# chrome_options.add_argument("--disable-cloud-import")
# chrome_options.add_argument("--disable-popup-blocking")
# chrome_options.add_argument("--ignore-certificate-errors")
# chrome_options.add_argument("--disable-session-crashed-bubble")
# chrome_options.add_argument("--disable-ipv6")
# chrome_options.add_argument("--allow-http-screen-capture")
# chrome_options.add_argument("--start-maximized")
chrome_options.add_argument('--user-agent={}'.format('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36'))
# chrome_options.add_argument('--headless')


driver = webdriver.Chrome("chromedriver.exe",options=chrome_options)
# driver = webdriver.Chrome("chromedriver.exe")


# driver.get("https://www.realestate.com.au/149e9513-01fa-4fb0-aad4-566afd725d1b/2d206a39-8ed7-437e-a3be-862e0f06eea3/fingerprint")
# driver.get("https://www.realestate.com.au/125666126")
driver.get("https://www.realestate.com.au/sold/property-unit-qld-surfers+paradise-125666126")

# time.sleep(60)
# driver.save_screenshot('sample_screenshot.png')

#storing the cookies generated by the browser
request_cookies_browser = driver.get_cookies()
print(request_cookies_browser)

s = requests.Session()

#passing the cookies generated from the browser to the session
c = [s.cookies.set(c['name'], c['value']) for c in request_cookies_browser]

resp = s.post("https://www.realestate.com.au/149e9513-01fa-4fb0-aad4-566afd725d1b/2d206a39-8ed7-437e-a3be-862e0f06eea3/fingerprint", {}) #I get a 200 status_code


# cookies = {} # scores is an empty dict already
# target = "cookies.pkl"
# if os.path.getsize(target) > 0:      
#     with open(target, "rb") as f:
#         unpickler = pickle.Unpickler(f)
#         # if file is not empty scores will be equal
#         # to the value unpickled
#         cookies = unpickler.load()

# # print(cookies)
# # cookies = pickle.load(open("cookies.pkl", "rb"))
for c in request_cookies_browser:
    driver.add_cookie({'name' : c['name'], 'value' : c['value']})
    # driver.get("https://www.realestate.com.au/125666126")
    driver.get("https://www.realestate.com.au/149e9513-01fa-4fb0-aad4-566afd725d1b/2d206a39-8ed7-437e-a3be-862e0f06eea3/fingerprint")

# time.sleep(60)
# driver.save_screenshot('sample_screenshot1.png')

request_cookies_browser = driver.get_cookies()
for c in request_cookies_browser:
    driver.add_cookie({'name' : c['name'], 'value' : c['value']})
    # driver.get("https://www.realestate.com.au/125666126")
    driver.get("https://www.realestate.com.au/sold/property-unit-qld-surfers+paradise-125666126")

# time.sleep(100)
# driver.quit()